# Site settings
title: "Realitix's blog"
email: realitix@gmail.com
description: "Technical blog about things I enjoy"
baseurl: ""
url: "https://realitix.github.io"
title_description: 'Deep into the bowels of code !'
title_image: "/img/avatar.png"
github_repository: https://github.com/realitix
post_limit: 20

# Social usernames/URLs
twitter_username: realitix
github_username:  realitix
stackoverflow_link: "http://stackoverflow.com/users/3327268/realitix"

# Footer
footer_left: "Made with <b>passion</b> by Jean-Sebastien Bevilacqua"
footer_right: "Follow me on <a href=\"https://github.com/realitix\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
